<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="PRG_AT1K4_SOLID" Id="{ea78c8b5-92ba-4f6a-a34a-74754b259467}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_AT1K4_SOLID
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// M2, Axis 2
// M3, Axis 3
// M4, Axis 4
// M5, Axis 5]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>